-- Kria KV260 top level. Blinks PMOD J2 pin 1 at 1 Hz.

library ieee;
use ieee.std_logic_1164.all;

library olo;


entity kv260_top is
  port (
    pmod : out std_ulogic_vector(0 downto 0) := (others => '0')
  );
end entity;

architecture a of kv260_top is

  -- Generated by Vivado from tcl/block_design.tcl.
  component block_design is
    port (
      pl_clk0 : out std_ulogic;
      pl_resetn0 : out std_ulogic
    );
  end component;

  signal clk, resetn, rst, toggle : std_ulogic := '0';

begin

  -- The block design only exists inside Vivado, so there is no entity to instantiate.
  -- vsg_off instantiation_034
  block_design_inst : component block_design
    port map (
      pl_clk0 => clk,
      pl_resetn0 => resetn
    );
  -- vsg_on instantiation_034

  reset_gen_inst : entity olo.olo_base_reset_gen
    generic map (
      RstInPolarity_g => '0'
    )
    port map (
      Clk => clk,
      RstIn => resetn,
      RstOut => rst
    );

  strobe_gen_inst : entity olo.olo_base_strobe_gen
    generic map (
      FreqClkHz_g => 100.0e6,
      FreqStrobeHz_g => 2.0
    )
    port map (
      Clk => clk,
      Rst => rst,
      Out_Valid => toggle
    );

  blink : process
  begin
    wait until rising_edge(clk);

    if toggle then
      pmod(0) <= not pmod(0);
    end if;

    if rst then
      pmod(0) <= '0';
    end if;
  end process;

end architecture;
